DAY 11-Web API ,DTO&Auto Mapping Class Exercise & Assignment/Assignment_CodeFirstApproach/Controllers/AppointmentsController.cs
using Assignment_CodeFirstApproach.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Assignment_CodeFirstApproach.Controllers

{
    public class AppointmentsController : Controller
    {
        private readonly MyContext _context;

        public AppointmentsController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var appointments = _context.Appointments.Include(a => a.Doctor).Include(a => a.Patient).ToList();
            return View(appointments);
        }
        public IActionResult Details(int id)
        {
            var appointment = _context.Appointments.Include(a => a.Doctor).Include(a => a.Patient).FirstOrDefault(a => a.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }

        public IActionResult Create()
        {
            ViewBag.Doctors = new SelectList(_context.Doctors, "DoctorId", "Name");
            ViewBag.Patients = new SelectList(_context.Patients, "PatientId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Appointment appointment)
        {
            if (!ModelState.IsValid)
            {
                _context.Appointments.Add(appointment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            // Repopulate the dropdowns in case of an error.
            ViewBag.Doctors = new SelectList(_context.Doctors, "DoctorId", "Name");
            ViewBag.Patients = new SelectList(_context.Patients, "PatientId", "Name");
            return View(appointment);
        }


        public IActionResult Edit(int id)
        {
            var appointment = _context.Appointments.Find(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewBag.DoctorId = new SelectList(_context.Doctors, "DoctorId", "Name");
            ViewBag.PatientId = new SelectList(_context.Patients, "PatientId", "Name");
            return View(appointment);
        }

        [HttpPost]
        public IActionResult Edit(Appointment appointment)
        {
            if (!ModelState.IsValid)
            {
                _context.Appointments.Update(appointment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DoctorId = new SelectList(_context.Doctors, "DoctorId", "Name");
            ViewBag.PatientId = new SelectList(_context.Patients, "PatientId", "Name");
            return View(appointment);
        }

        public IActionResult Delete(int id)
        {
            var appointment = _context.Appointments.Include(a => a.Doctor).Include(a => a.Patient).FirstOrDefault(a => a.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var appointment = _context.Appointments.Find(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DAY 11-Web API ,DTO&Auto Mapping Class Exercise & Assignment/Assignment_CodeFirstApproach/Controllers/DoctorsController.cs
using Assignment_CodeFirstApproach.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Assignment_CodeFirstApproach.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly MyContext _context;

        public DoctorsController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var doctors = _context.Doctors.Include(d => d.Hospital).ToList();
            return View(doctors);
        }
        public IActionResult Details(int id)
        {
            var doctor = _context.Doctors.Include(d => d.Hospital).Include(d => d.Appointments).ThenInclude(a => a.Patient).FirstOrDefault(d => d.DoctorId == id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }


        public IActionResult Create()
        {
            ViewBag.Hospitals = new SelectList(_context.Hospitals, "HospitalId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                _context.Doctors.Add(doctor);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            // Repopulate the dropdown in case of an error.
            ViewBag.Hospitals = new SelectList(_context.Hospitals, "HospitalId", "Name");
            return View(doctor);
        }


        public IActionResult Edit(int id)
        {
            var doctor = _context.Doctors.Find(id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewBag.HospitalId = new SelectList(_context.Hospitals, "HospitalId", "Name");
            return View(doctor);
        }

        [HttpPost]
        public IActionResult Edit(Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                _context.Doctors.Update(doctor);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HospitalId = new SelectList(_context.Hospitals, "HospitalId", "Name");
            return View(doctor);
        }

        public IActionResult Delete(int id)
        {
            var doctor = _context.Doctors.Include(d => d.Hospital).FirstOrDefault(d => d.DoctorId == id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var doctor = _context.Doctors.Find(id);
            if (doctor != null)
            {
                _context.Doctors.Remove(doctor);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DAY 11-Web API ,DTO&Auto Mapping Class Exercise & Assignment/Assignment_CodeFirstApproach/Controllers/HospitalsController.cs
using Assignment_CodeFirstApproach.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment_CodeFirstApproach.Controllers
{
    public class HospitalsController : Controller
    {
        private readonly MyContext _context;

        public HospitalsController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var hospitals = _context.Hospitals.ToList();
            return View(hospitals);
        }

        public IActionResult Details(int id)
        {
            var hospital = _context.Hospitals.Include(h => h.Doctors).FirstOrDefault(h => h.HospitalId == id);
            if (hospital == null)
            {
                return NotFound();
            }
            return View(hospital);
        }

        // GET: Hospital/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hospital/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Hospital hospital)
        {
            if (!ModelState.IsValid)
            {
                _context.Hospitals.Add(hospital);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital);
        }


        public IActionResult Edit(int id)
        {
            var hospital = _context.Hospitals.Find(id);
            if (hospital == null)
            {
                return NotFound();
            }
            return View(hospital);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Hospital hospital)
        {
            if (!ModelState.IsValid)
            {
                _context.Hospitals.Update(hospital);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hospital);
        }

        public IActionResult Delete(int id)
        {
            var hospital = _context.Hospitals.Find(id);
            if (hospital == null)
            {
                return NotFound();
            }
            return View(hospital);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var hospital = _context.Hospitals.Find(id);
            if (hospital != null)
            {
                _context.Hospitals.Remove(hospital);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DAY 11-Web API ,DTO&Auto Mapping Class Exercise & Assignment/Assignment_CodeFirstApproach/Controllers/PatientsController.cs
using Assignment_CodeFirstApproach.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Assignment_CodeFirstApproach.Controllers
{
    public class PatientsController : Controller
    {
        private readonly MyContext _context;

        public PatientsController(MyContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var patients = _context.Patients.ToList();
            return View(patients);
        }

        public IActionResult Details(int id)
        {
            var patient = _context.Patients.Include(p => p.Appointments).ThenInclude(a => a.Doctor).FirstOrDefault(p => p.PatientId == id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Patient patient)
        {
            if (!ModelState.IsValid)
            {
                _context.Patients.Add(patient);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        public IActionResult Edit(int id)
        {
            var patient = _context.Patients.Find(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Patient patient)
        {
            if (!ModelState.IsValid)
            {
                _context.Patients.Update(patient);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        public IActionResult Delete(int id)
        {
            var patient = _context.Patients.Find(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var patient = _context.Patients.Find(id);
            if (patient != null)
            {
                _context.Patients.Remove(patient);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DAY 11-Web API ,DTO&Auto Mapping Class Exercise & Assignment/Assignment_CodeFirstApproach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment_CodeFirstApproach</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment_CodeFirstApproach.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment_CodeFirstApproach</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">Doctors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitals" asp-action="Index">Hospitals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index">Patients</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Assignment_CodeFirstApproach - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>